### ISSUE TITLE
Parsing ocr.space API response

### ISSUE THREAD

**Issue by QoT** [A9T9/OCR-API-Draw-Overlay#1]
Code works fine except one typo, I would say. Looks like Python code expects `Overlay` while API output renders `TextOverlay`.

Probably line #67:
`    for line in pr["Overlay"]["Lines"]:
`

Should be:
`    for line in pr["TextOverlay"]["Lines"]:
`

You can see that in live [API demo response](https://api.ocr.space/parse/imageurl?apikey=helloworld&url=http://i.imgur.com/fwxooMv.png) which should be the latest version, I guess.

Once changed that, code works fine.

**Comment by A9T9** [comment]
Thanks for reporting => fixed!
